In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/heart.csv')
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [9]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [10]:
data[data.duplicated()]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
15,34,0,1,118,210,0,1,192,0,0.7,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
43,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
55,55,1,0,140,217,0,1,111,1,5.6,0,0,3,0
61,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data[data.duplicated()]

Empty DataFrame
Columns: [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal, target]
Index: []

In [13]:
X=data[['age','sex','cp','trestbps','chol','thalach','exang','oldpeak']]
y=data['target']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [16]:
model=LinearRegression()
model.fit(X_train_scaled,y_train)

LinearRegression()

In [17]:
y_pred_train=model.predict(X_train_scaled)
y_pred_test=model.predict(X_test_scaled)

In [18]:
print("Training Result:")
print("RMSE:",np.sqrt(mean_squared_error(y_train,y_pred_train)))
print("MAE:",mean_absolute_error(y_train,y_pred_train))
print("R2 Score:",r2_score(y_train,y_pred_train))
print("Testing Result:")
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_pred_test)))
print("MAE:",mean_absolute_error(y_test,y_pred_test))

Training Result:
RMSE: 0.35470450994058905
MAE: 0.2862544016379135
R2 Score: 0.4893446665250617
Testing Result:
RMSE: 0.428755351096668
MAE: 0.3616053472755507

In [19]:
modellogistic=LogisticRegression()
modellogistic.fit(X_train_scaled,y_train)

LogisticRegression()

In [20]:
y_pred_train=modellogistic.predict(X_train_scaled)
y_pred_test=modellogistic.predict(X_test_scaled)

In [21]:
print("Training Result:")
print("RMSE:",np.sqrt(mean_squared_error(y_train,y_pred_train)))
print("MAE:",mean_absolute_error(y_train,y_pred_train))
print("R2 Score:",r2_score(y_train,y_pred_train))
print("Testing Result:")
print("RMSE:",np.sqrt(mean_squared_error(y_test,y_pred_test)))
print("MAE:",mean_absolute_error(y_test,y_pred_test))
print("R2 Score:",r2_score(y_test,y_pred_test))

Training Result:
RMSE: 0.40227568425282534
MAE: 0.16182572614107885
R2 Score: 0.3431865828092244
Testing Result:
RMSE: 0.5279095799378564
MAE: 0.2786885245901639
R2 Score: -0.11745689655172398

In [22]:
feature_importance=pd.DataFrame({
    "Feature":X_train.columns,
    "Coefficient":modellogistic.coef_[0]
})
feature_importance.sort_values(by="Coefficient",ascending=False)

    Feature  Coefficient
2        cp     0.997212
5   thalach     0.598759
0       age    -0.183211
4      chol    -0.202716
6     exang    -0.233871
3  trestbps    -0.580444
7   oldpeak    -0.975025
1       sex    -1.033896

In [23]:
data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.602649,246.500000,0.149007,0.526490,149.569536,0.327815,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,0.466426,1.032044,17.563394,51.753489,0.356686,0.526027,22.903527,0.470196,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [24]:
comparison=pd.DataFrame({
    "Actual":y_test,
    "Predicted":y_pred_test
})
comparison.head(10)

     Actual  Predicted
245       1          1
349       0          1
135       0          0
389       1          1
66        1          1
9         0          0
145       0          0
337       1          1
498       1          0
35        0          0

In [25]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'C': [0.001, 0.01, 0.1, 1,10]
}
grid = GridSearchCV(
    LogisticRegression(),
    param_grid=param_grid,
    cv=5,
    scoring='r2'
)
grid.fit(X_train_scaled, y_train)
print("Best C:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best C: {'C': 1}
Best Score: 0.24285714285714288

In [26]:
X.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'thalach', 'exang', 'oldpeak'], dtype='object')

In [27]:
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
733,44,0,2,108,141,0,1,175,0,0.6,1,0,2,1
739,52,1,0,128,255,0,1,161,1,0.0,2,1,3,0
843,59,1,3,160,273,0,0,125,0,0.0,2,0,2,0
878,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [28]:
import pandas as pd

feature_columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'thalach', 'exang', 'oldpeak']
new_data_list = [[
    50,    # age
    0,     # sex (Female - contributes positively to prediction 1 due to negative coefficient)
    3,     # cp (Typical Angina - strong positive coefficient)
    120,   # trestbps
    180,   # chol
    180,   # thalach (high value, strong positive coefficient)
    0,     # exang (No exercise induced angina - contributes positively to prediction 1 due to negative coefficient)
    0.0    # oldpeak (low value, strong positive effect for prediction 1 due to negative coefficient)
]]

new_data_df = pd.DataFrame(new_data_list, columns=feature_columns)
new_data_scaled = scalar.transform(new_data_df)

prediction = modellogistic.predict(new_data_scaled)
print(prediction)
if prediction[0] == 1:
    print("Heart Disease Detected")
else:
    print("No Heart Disease")

[1]
Heart Disease Detected

In [29]:
import pickle

In [30]:
with open("model.pkl","wb") as f:
  pickle.dump(modellogistic,f)

In [31]:
with open("model.pkl","rb") as f:
  model=pickle.load(f)